name       : hunspell-en
version    : 2018.04.16
release    : 5
source     :
    - https://netcologne.dl.sourceforge.net/project/wordlist/speller/2018.04.16/hunspell-en_GB-large-2018.04.16.zip : b19e51a95d85c103b545f9d9a621febfdd8cf706358138748038c4bd4b3f8df8
    - https://netix.dl.sourceforge.net/project/wordlist/speller/2018.04.16/hunspell-en_US-2018.04.16.zip : 4efdba6438b916a61c4a12933952f458564f2f2af3db9ab3c27f328b37b30ba2
    - https://netcologne.dl.sourceforge.net/project/wordlist/speller/2018.04.16/hunspell-en_CA-2018.04.16.zip : 87b06d6aa41f41f59c1c7c9843ae66232824896528e83563952588e08f1ece1b
license    : BSD-3-Clause
component  : office.spelling
summary    : English hunspell dictionaries
description: |
    English hunspell dictionaries
rundeps    :
    - libhunspell
setup      : |
    unzip $sources/hunspell-en_US-$version.zip
    unzip $sources/hunspell-en_CA-$version.zip
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    install -m 00644 en_*.dic en_*.aff $installdir/usr/share/hunspell

    pushd $installdir/usr/share/hunspell/
    en_GB_aliases="en_AG en_AU en_BS en_BW en_BZ en_DK en_GB en_GH en_HK en_IE en_IN en_JM en_NA en_NG en_NZ en_SG en_TT en_ZA en_ZW"
    for lang in $en_GB_aliases; do
        ln -s en_GB-large.aff $lang.aff
        ln -s en_GB-large.dic $lang.dic
    done
    ln -s en_US.aff en_PH.aff
    ln -s en_US.dic en_PH.dic
    popd
    # The joy of zip sources
    chmod 00644 $installdir/usr/share/hunspell/*.{aff,dic}
