name       : hunspell-en
version    : 2016.06.26
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/wordlist/speller/2016.06.26/hunspell-en_GB-large-2016.06.26.zip : 68c0035d6ee49eef8dee4869818b8088817250ec61a22bd1b48979994818241f
    - http://vorboss.dl.sourceforge.net/project/wordlist/speller/2016.06.26/hunspell-en_US-2016.06.26.zip : fd3827f91a609a4e9d3d0dbcf4b1d450667af26d15199de4812eeb88304dcd3f
    - http://netcologne.dl.sourceforge.net/project/wordlist/speller/2016.06.26/hunspell-en_CA-2016.06.26.zip : 5ea189fe8159d16b4acdf1a2fef5a27fb62a3c861c62555a995c4b056a9c766a
license    : BSD-3-Clause
component  : spelling
summary    : English hunspell dictionaries
description: |
    English hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -d -m 00644 $installdir/usr/share/hunspell
    install -m 00644 en_*.dic en_*.aff $installdir/usr/share/hunspell

    pushd $installdir/usr/share/hunspell/
    en_GB_aliases="en_AG en_AU en_BS en_BW en_BZ en_DK en_GB en_GH en_HK en_IE en_IN en_JM en_NA en_NG en_NZ en_SG en_TT en_ZA en_ZW"
    for lang in $en_GB_aliases; do
        ln -s en_GB-large.aff $lang.aff
        ln -s en_GB-large.dic $lang.dic
    done
    ln -s en_US.aff en_PH.aff
    ln -s en_US.dic en_PH.dic
    popd
