name       : hunspell-en
version    : 2017.08.24
release    : 3
source     :
    - https://netcologne.dl.sourceforge.net/project/wordlist/speller/2017.08.24/hunspell-en_GB-large-2017.08.24.zip : e87dd193af8b1a7d0076faf0aa112fa22925868366d56b045d69fc1d93c4b94e
    - https://netix.dl.sourceforge.net/project/wordlist/speller/2017.08.24/hunspell-en_US-2017.08.24.zip : c59ae3f0a597358f7c613ada2875a8d8313a5a80496077ab7ed6a030bf1702b1
    - https://netcologne.dl.sourceforge.net/project/wordlist/speller/2017.08.24/hunspell-en_CA-2017.08.24.zip : 0e404afd5f2f442b1ec60c9a540bd4fdfb429c5a036b78c952d764290d6991ff
license    : BSD-3-Clause
component  : spelling
summary    : English hunspell dictionaries
description: |
    English hunspell dictionaries
rundeps    :
    - libhunspell
setup      : |
    unzip $sources/hunspell-en_US-$version.zip
    unzip $sources/hunspell-en_CA-$version.zip
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    install -m 00644 en_*.dic en_*.aff $installdir/usr/share/hunspell

    pushd $installdir/usr/share/hunspell/
    en_GB_aliases="en_AG en_AU en_BS en_BW en_BZ en_DK en_GB en_GH en_HK en_IE en_IN en_JM en_NA en_NG en_NZ en_SG en_TT en_ZA en_ZW"
    for lang in $en_GB_aliases; do
        ln -s en_GB-large.aff $lang.aff
        ln -s en_GB-large.dic $lang.dic
    done
    ln -s en_US.aff en_PH.aff
    ln -s en_US.dic en_PH.dic
    popd
    # The joy of zip sources
    chmod 00644 $installdir/usr/share/hunspell/*.{aff,dic}
